### ISSUE TITLE
Face ValueError when running 01_spam_tutorial.py

### ISSUE THREAD

**Issue by Wilson-ZHANG** [snorkel-team/snorkel-tutorials#179]
#### in snorkel-tutorials/span/01_spam_tutorial.py
line 789, df_fn_dev.sample(5, random_state=3)

Face ValueError: Cannot take a larger sample than population when 'replace=False'

## Code example/repro steps
I do not modify any code in this python file.

## Expected behavior
I want to know whether there is something error in my code environment.

## Screenshots
The whole log is below.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/18693151/69611549-f9188b80-1068-11ea-8f91-d741aa2ab919.png">

## System info

* How you installed Snorkel (conda, pip, source): Pycharm venv, like conda
* Build command you used (if compiling from source): Pycharm
* OS: macOS Mojave 10.14.6
* Python version: Python3.7.3
* Snorkel version: 0.9.3
* Versions of any other relevant libraries: all relevant libraries are installed by requirements.txt in this repo.

## Additional context
Of course, when I comment this line, the python file runs **successfully**.

**Comment by bhancock8** [comment]
I tried rerunning the tutorial myself (from current master) and couldn't reproduce. The error is arising because in your notebook, the false-positives error bucket has fever than five examples. When I ran the notebook, that bucket had exactly five examples. The errors _should_ be the same every time the notebook is run, since we set random seeds. Try running the tutorial again and if it errs again, can you report back with how many examples are in that bucket (`len(df_fn_dev)`) and what the reported accuracy scores are for the `Majority Vote Accuracy` and `Label Model Accuracy` above that?

**Comment by Wilson-ZHANG** [comment]
len（df_fn_dev) equals to 3, not 5. I re-cloned this repo, re-installed environment by requirements.txt.
The following is output:
Majority Vote Accuracy:   90.4%
Label Model Accuracy:     90.5%
len of df_fn_dev: 3
                                                  text  label  probability
313                     Aslamu Lykum... From Pakistan﻿      1          0.0
189          /watch?v=aImbWbfQbzg watch and subscrible      1          0.0
334  Check out Em&#39;s dope new song monster here:...      1          0.0
