### ISSUE TITLE
What is .text in the Get Started tutorial?

### ISSUE THREAD

**Issue by changhsinlee** [snorkel-team/snorkel-tutorials#183]
## Issue description

When I read through https://www.snorkel.org/get-started/, by the end I got really confused about why there is a `.text` attribute.

What is `df_train_augmented.text` in 5) Training a Classifier? Pandas dataframe doesn't have a `.text` attribute so I feel I must have missed something.

I looked back and realized all the labeling functions also return an object that used `.text` attribute in there, and now I'm more confused if I understand how to write a labeling function at all. Are they applying to a column of the dataframe or a very specific type of object?

## Code example/repro steps

Current code in *5) Training a Classifier*

```py
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression

train_text = df_train_augmented.text.tolist() # this is where I'm confused
X_train = CountVectorizer(ngram_range=(1, 2)).fit_transform(train_text)

clf = LogisticRegression(solver="lbfgs")
clf.fit(X=X_train, y=df_train_augmented.label.values)
```

**Comment by changhsinlee** [comment]
I saw this:
https://www.snorkel.org/use-cases/01-spam-tutorial#a-exploring-the-development-set-for-initial-ideas

Is `.text` referring to a column in the pandas dataframe? 

If so, can we change the wording in the tutorial to use `df['text']` instead of `df.x`? Adding type annotation to the labeling functions may have helped me understand better if that's the case e.g.

* Before

```py
@labeling_function()
def lf_contains_link(x):
    # Return a label of SPAM if "http" in comment text, otherwise ABSTAIN
    return SPAM if "http" in x.text.lower() else ABSTAIN
```

* After

```py
@labeling_function()
def lf_contains_link(x: pd.DataFrame):
    # Return a label of SPAM if "http" in comment text, otherwise ABSTAIN
    return SPAM if "http" in x.text.lower() else ABSTAIN
```

**Comment by paroma** [comment]
`x.text` is referring to a column in the Pandas DataFrame as @changhsinlee said. We would be happy to incorporate a PR that edits the tutorial to clarify where `.text` comes from!

We stick to this specific syntax since `x` does not necessarily have to be a Pandas DataFrame (e.g., it could be a [Spark RDD](https://snorkel.readthedocs.io/en/v0.9.3/packages/_autosummary/labeling/snorkel.labeling.apply.spark.SparkLFApplier.html)). Keeping the syntax independent of the type of `x` helps maintain flexibility in terms of how LFs can be applied to different data types without need editing the LFs themselves.

**Comment by henryre** [comment]
Just to tack on to @paroma's comment: we avoid type annotations for LFs so that they're compatible across core data structures like she said, but if you're using a Pandas DataFrame and `PandasLFApplier`, the type annotation would be

```python
@labeling_function()
def lf_contains_link(x: pd.Series):
    ...
```

since rows of DataFrames are represented as Series on iteration. Closing this issue out but feel free to reopen if needed.
