### ISSUE TITLE
why ...fit(L_train, Y_dev) ?

### ISSUE THREAD

**Issue by rschmaelzle** [snorkel-team/snorkel-tutorials#190]
## Issue description
---A clear and concise description of what the bug is.
Hi, in the /spouse_demo.ipynb in cell 19, the training model is fit with (L_train, Y_dev). 

Perhaps I am missing something, but I didn't understand why that was the case.
thank you and best. R

**Comment by henryre** [comment]
Hi @rschmaelzle, great question. If we have some ground truth labels available (here stored in `Y_dev`), we can use them to better estimate class balance (see https://snorkel.readthedocs.io/en/v0.9.3/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel.fit). Since this is inferred using only the labels, they don't need to correspond to the label matrix used to train the label model (here `L_train`). Feel free to reopen if you have more questions!
